//go:build integration

package integration

import (
	"context"
	"fmt"
	"os"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"

	"github.com/elqsar/pganalyzer/internal/analyzer"
	"github.com/elqsar/pganalyzer/internal/collector"
	"github.com/elqsar/pganalyzer/internal/collector/risk"
	"github.com/elqsar/pganalyzer/internal/models"
	"github.com/elqsar/pganalyzer/internal/postgres"
	"github.com/elqsar/pganalyzer/internal/storage/sqlite"
	"github.com/elqsar/pganalyzer/internal/suggester"
	"github.com/elqsar/pganalyzer/internal/suggester/rules"
)

// TestOutageRisk checks the outage-risk queries against a real server and runs
// them through collection, analysis and the rules.
//
// A prepared transaction is only created when the server allows them
// (-c max_prepared_transactions=10); wraparound ages cannot be pushed near their
// thresholds here, so only their plausibility is checked.
func TestOutageRisk(t *testing.T) {
	host := os.Getenv("POSTGRES_HOST")
	if host == "" {
		t.Skip("set POSTGRES_HOST to run the PostgreSQL integration test")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()

	port, err := strconv.Atoi(envOr("POSTGRES_PORT", "5432"))
	if err != nil {
		t.Fatal(err)
	}
	dbName := envOr("POSTGRES_DATABASE", "testdb")
	pg, err := postgres.NewClient(postgres.ClientConfig{
		Host: host, Port: port, Database: dbName,
		User: envOr("POSTGRES_USER", "postgres"), Password: envOr("POSTGRES_PASSWORD", "postgres"),
		SSLMode: envOr("POSTGRES_SSLMODE", "disable"), ConnectTimeout: 5 * time.Second,
	})
	if err != nil {
		t.Fatal(err)
	}
	if err := pg.Connect(ctx); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { pg.Close() })

	connect := func() *pgx.Conn {
		conn, err := pgx.Connect(ctx, fmt.Sprintf("host=%s port=%d dbname=%s user=%s password=%s sslmode=%s",
			host, port, dbName, envOr("POSTGRES_USER", "postgres"),
			envOr("POSTGRES_PASSWORD", "postgres"), envOr("POSTGRES_SSLMODE", "disable")))
		if err != nil {
			t.Fatal(err)
		}
		return conn
	}
	conn := connect()

	const (
		schema = "pgk_outage_risk"
		slot   = "pgk_it_slot"
		gid    = "pgk_it_prepared"
	)
	cleanup := func() {
		bg := context.Background()
		_, _ = conn.Exec(bg, "ROLLBACK PREPARED '"+gid+"'")
		_, _ = conn.Exec(bg, "SELECT pg_drop_replication_slot(slot_name) FROM pg_replication_slots WHERE slot_name = '"+slot+"'")
		_, _ = conn.Exec(bg, "DROP SCHEMA IF EXISTS "+schema+" CASCADE")
	}
	cleanup()
	t.Cleanup(func() {
		cleanup()
		conn.Close(context.Background())
	})

	for _, stmt := range []string{
		"CREATE SCHEMA " + schema,
		// serial: an integer sequence at 93% of its range.
		"CREATE TABLE " + schema + ".orders (id serial PRIMARY KEY, note text)",
		"SELECT setval('" + schema + ".orders_id_seq', 2000000000)",
		// A bigint sequence feeding an integer column: limited by the column type.
		"CREATE TABLE " + schema + ".events (id int PRIMARY KEY)",
		"CREATE SEQUENCE " + schema + ".events_id_seq AS bigint OWNED BY " + schema + ".events.id",
		"SELECT setval('" + schema + ".events_id_seq', 1700000000)",
		// An identity column at 60%: below the warning threshold.
		"CREATE TABLE " + schema + ".items (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)",
		"SELECT setval(pg_get_serial_sequence('" + schema + ".items', 'id'), 1300000000)",
		// A bigint column far from its limit must not be reported as used up.
		"CREATE TABLE " + schema + ".big (id bigserial PRIMARY KEY)",
		"SELECT setval('" + schema + ".big_id_seq', 2000000000)",
		"SELECT pg_create_physical_replication_slot('" + slot + "', true)",
	} {
		if _, err := conn.Exec(ctx, stmt); err != nil {
			t.Fatalf("%s: %v", stmt, err)
		}
	}

	var maxPrepared int
	if err := conn.QueryRow(ctx, "SELECT current_setting('max_prepared_transactions')::int").Scan(&maxPrepared); err != nil {
		t.Fatal(err)
	}
	if maxPrepared > 0 {
		prep := connect()
		for _, stmt := range []string{"BEGIN", "INSERT INTO " + schema + ".orders (note) VALUES ('x')", "PREPARE TRANSACTION '" + gid + "'"} {
			if _, err := prep.Exec(ctx, stmt); err != nil {
				t.Fatalf("%s: %v", stmt, err)
			}
		}
		prep.Close(ctx)
	} else {
		t.Log("max_prepared_transactions = 0; skipping the prepared transaction check")
	}

	got, err := pg.GetOutageRisk(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Unavailable) != 0 {
		t.Errorf("checks unavailable as superuser: %v", got.Unavailable)
	}
	if got.InRecovery || got.Database != dbName || got.FreezeMaxAge <= 0 || got.MultixactFreezeMaxAge <= 0 {
		t.Errorf("header = in_recovery %v, database %q, freeze max ages %d/%d", got.InRecovery, got.Database, got.FreezeMaxAge, got.MultixactFreezeMaxAge)
	}
	var sawDB bool
	for _, d := range got.Databases {
		if d.XIDAge < 0 || d.XIDAge > 2_000_000_000 || d.MXIDAge < 0 {
			t.Errorf("implausible ages: %+v", d)
		}
		sawDB = sawDB || d.Name == dbName
	}
	if !sawDB || len(got.OldestTables) == 0 {
		t.Errorf("wraparound: databases %+v, %d oldest tables", got.Databases, len(got.OldestTables))
	}
	if got.DatabaseSize <= 0 || got.ClusterSize < got.DatabaseSize {
		t.Errorf("sizes: database %d, cluster %d", got.DatabaseSize, got.ClusterSize)
	}

	var gotSlot *models.ReplicationSlot
	for i := range got.Slots {
		if got.Slots[i].Name == slot {
			gotSlot = &got.Slots[i]
		}
	}
	if gotSlot == nil || gotSlot.Active || gotSlot.Type != "physical" || gotSlot.RetainedBytes == nil || gotSlot.WALStatus == "" {
		t.Errorf("slot = %+v", gotSlot)
	}

	seqs := make(map[string]models.SequenceUsage)
	for _, s := range got.Sequences {
		if s.SchemaName == schema {
			seqs[s.SequenceName] = s
		}
	}
	if s := seqs["orders_id_seq"]; s.TableName != "orders" || s.ColumnName != "id" || s.ColumnType != "integer" || s.MaxValue != 2147483647 || s.UsedFraction < 0.93 {
		t.Errorf("orders_id_seq = %+v", s)
	}
	if s := seqs["events_id_seq"]; s.ColumnType != "integer" || s.MaxValue != 2147483647 || s.UsedFraction < 0.79 {
		t.Errorf("events_id_seq = %+v", s)
	}
	if s := seqs["items_id_seq"]; s.ColumnName != "id" || s.UsedFraction < 0.6 || s.UsedFraction > 0.61 {
		t.Errorf("items_id_seq (identity) = %+v", s)
	}
	if s, ok := seqs["big_id_seq"]; ok && s.UsedFraction > 0.01 {
		t.Errorf("bigint sequence judged against the wrong limit: %+v", s)
	}

	if maxPrepared > 0 {
		var found bool
		for _, p := range got.PreparedXacts {
			if p.GID == gid {
				found = p.Database == dbName && p.XIDAge >= 0 && time.Since(p.Prepared) < time.Minute
			}
		}
		if !found {
			t.Errorf("prepared transaction %s not reported: %+v", gid, got.PreparedXacts)
		}
	}

	// Collection -> analysis -> rules.
	storage, err := sqlite.NewStorage(t.TempDir() + "/risk.db")
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { storage.Close() })
	instanceID, err := storage.CreateInstance(ctx, &models.Instance{Name: "risk", Host: host, Port: port, Database: dbName})
	if err != nil {
		t.Fatal(err)
	}
	coord := collector.NewCoordinator(collector.CoordinatorConfig{PGClient: pg, Storage: storage, InstanceID: instanceID})
	coord.RegisterCollectors(risk.NewCollector(risk.Config{PGClient: pg, Storage: storage, InstanceID: instanceID}))
	collected, err := coord.CollectAll(ctx)
	if err != nil {
		t.Fatal(err)
	}
	if collected.HasErrors() {
		t.Fatal(collected.Error())
	}
	if history, err := storage.GetSizeHistory(ctx, instanceID, time.Now().Add(-time.Hour)); err != nil || len(history) != 1 {
		t.Fatalf("size history = %+v, %v", history, err)
	}

	analyzerConfig := analyzer.DefaultConfig()
	analyzerConfig.CollectorIntervals = coord.CollectorIntervals()
	analysis, err := analyzer.NewMainAnalyzer(storage, analyzerConfig).Analyze(ctx, collected.SnapshotID)
	if err != nil {
		t.Fatal(err)
	}
	if !analysis.DomainsUsable(analyzer.DomainOutageRisk) || analysis.Risk == nil {
		t.Fatalf("outage risk not analysed: errors=%v coverage=%+v", analysis.Errors, analysis.Coverage)
	}

	suggestConfig := suggester.DefaultConfig()
	sug := suggester.NewSuggester(storage, suggestConfig, nil)
	sug.RegisterRules(
		rules.NewXIDWraparoundRule(suggestConfig),
		rules.NewMultixactWraparoundRule(suggestConfig),
		rules.NewReplicationSlotRule(suggestConfig),
		rules.NewSequenceExhaustionRule(suggestConfig),
		rules.NewPreparedTransactionRule(suggestConfig),
	)
	if _, err := sug.Suggest(ctx, analysis); err != nil {
		t.Fatal(err)
	}
	active, err := storage.GetSuggestionsByStatus(ctx, instanceID, models.StatusActive)
	if err != nil {
		t.Fatal(err)
	}
	bySeverity := make(map[string]string)
	for _, s := range active {
		bySeverity[s.RuleID+" "+s.TargetObject] = s.Severity
	}
	if sev := bySeverity["sequence_exhaustion sequence:"+schema+".orders_id_seq"]; sev != models.SeverityCritical {
		t.Errorf("orders_id_seq severity = %q; active: %v", sev, bySeverity)
	}
	if sev := bySeverity["sequence_exhaustion sequence:"+schema+".events_id_seq"]; sev != models.SeverityWarning {
		t.Errorf("events_id_seq severity = %q; active: %v", sev, bySeverity)
	}
	for key := range bySeverity {
		if strings.HasPrefix(key, "xid_wraparound") || strings.HasPrefix(key, "sequence_exhaustion sequence:"+schema+".items") ||
			key == "replication_slot slot:"+slot {
			t.Errorf("unexpected suggestion on a fresh server: %s", key)
		}
	}
}
