// Package suggester provides a rules-based recommendation engine that generates
// actionable suggestions from analysis results.
package suggester

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/user/pganalyzer/internal/analyzer"
	"github.com/user/pganalyzer/internal/models"
)

// Severity levels for suggestions.
const (
	SeverityCritical = models.SeverityCritical
	SeverityWarning  = models.SeverityWarning
	SeverityInfo     = models.SeverityInfo
)

// Rule defines the interface for suggestion rules.
// Each rule evaluates analysis results and generates zero or more suggestions.
type Rule interface {
	// ID returns the unique identifier for this rule.
	ID() string

	// Name returns a human-readable name for this rule.
	Name() string

	// Evaluate analyzes the given AnalysisResult and returns suggestions.
	Evaluate(ctx context.Context, analysis *analyzer.AnalysisResult) ([]Suggestion, error)
}

// Suggestion represents a recommendation generated by a rule.
type Suggestion struct {
	RuleID       string                 // e.g., "slow_query", "unused_index"
	Severity     string                 // "critical", "warning", "info"
	Title        string                 // Short title for the suggestion
	Description  string                 // Detailed description with recommendations
	TargetObject string                 // table/index/query identifier
	Metadata     map[string]interface{} // Rule-specific additional data
}

// ToModel converts a Suggestion to a models.Suggestion for storage.
func (s *Suggestion) ToModel(instanceID int64) (*models.Suggestion, error) {
	metadataJSON, err := json.Marshal(s.Metadata)
	if err != nil {
		return nil, fmt.Errorf("marshaling metadata: %w", err)
	}

	return &models.Suggestion{
		InstanceID:   instanceID,
		RuleID:       s.RuleID,
		Severity:     s.Severity,
		Title:        s.Title,
		Description:  s.Description,
		TargetObject: s.TargetObject,
		Metadata:     string(metadataJSON),
	}, nil
}

// Config holds configuration for the suggester.
type Config struct {
	SlowQueryMs            float64 // queries slower than this are flagged
	SlowQueryCriticalMs    float64 // queries slower than this are critical
	CacheHitRatioWarning   float64 // warn below this ratio (0-1)
	CacheHitRatioCritical  float64 // critical below this ratio (0-1)
	BloatPercentWarning    float64 // tables with > this % bloat are warnings
	BloatPercentCritical   float64 // tables with > this % bloat are critical
	UnusedIndexDays        int     // days without scans
	SeqScanRatioWarning    float64 // seq_scan / total_scan ratio for warning
	SeqScanRatioCritical   float64 // seq_scan / total_scan ratio for critical
	MinTableSizeForIndex   int64   // skip index suggestions for tiny tables
	VacuumStaleDays        int     // days since last vacuum to consider stale

	// Operational thresholds
	LongRunningQuerySeconds      float64 // queries running longer flagged (warning)
	LongRunningCriticalSeconds   float64 // queries running longer are critical
	IdleInTxSeconds              float64 // idle-in-tx warning threshold
	IdleInTxCriticalSeconds      float64 // idle-in-tx critical threshold
	BlockedQuerySeconds          float64 // blocked query warning threshold
	BlockedQueryCriticalSeconds  float64 // blocked query critical threshold
	TempBytesWarning             int64   // temp bytes per snapshot warning
	TempBytesCritical            int64   // temp bytes per snapshot critical
	DeadlocksWarning             int64   // deadlocks per snapshot warning
	ConnectionUtilizationWarning float64 // connection utilization warning (0-1)
}

// DefaultConfig returns the default suggester configuration.
func DefaultConfig() *Config {
	return &Config{
		SlowQueryMs:           1000,  // 1 second
		SlowQueryCriticalMs:   5000,  // 5 seconds
		CacheHitRatioWarning:  0.95,  // 95%
		CacheHitRatioCritical: 0.90,  // 90%
		BloatPercentWarning:   20,    // 20%
		BloatPercentCritical:  50,    // 50%
		UnusedIndexDays:       30,    // 30 days
		SeqScanRatioWarning:   0.5,   // 50%
		SeqScanRatioCritical:  0.8,   // 80%
		MinTableSizeForIndex:  10000, // 10KB
		VacuumStaleDays:       7,     // 7 days

		// Operational defaults
		LongRunningQuerySeconds:      60,                      // 1 minute
		LongRunningCriticalSeconds:   300,                     // 5 minutes
		IdleInTxSeconds:              60,                      // 1 minute
		IdleInTxCriticalSeconds:      300,                     // 5 minutes
		BlockedQuerySeconds:          10,                      // 10 seconds
		BlockedQueryCriticalSeconds:  60,                      // 1 minute
		TempBytesWarning:             1024 * 1024 * 1024,      // 1GB
		TempBytesCritical:            10 * 1024 * 1024 * 1024, // 10GB
		DeadlocksWarning:             1,                       // any deadlocks
		ConnectionUtilizationWarning: 0.8,                     // 80%
	}
}
